<?php die( 'These aren\'t the droids you\'re looking for...' );
// extract of translatable text strings from static config array
_x( 'Accurate and complete meta tags for awesome looking shares on Facebook, Google, Pinterest, Twitter, etc - no matter how URLs are shared or re-shared!', 'plugin description', 'nextgen-facebook' );
_x( 'Additional Type URLs Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Admin Edit', 'option value', 'nextgen-facebook' );
_x( 'Advanced Settings', 'lib file description', 'nextgen-facebook' );
_x( 'All Buttons', 'option value', 'nextgen-facebook' );
_x( 'All Options', 'option value', 'nextgen-facebook' );
_x( 'All Transients', 'option label', 'nextgen-facebook' );
_x( 'All WP Objects', 'option label', 'nextgen-facebook' );
_x( 'Alpha and Up', 'option value', 'nextgen-facebook' );
_x( 'Any Platform', 'option value', 'nextgen-facebook' );
_x( 'Article Topics', 'option label', 'nextgen-facebook' );
_x( 'at', 'option value', 'nextgen-facebook' );
_x( 'Basic Options', 'option value', 'nextgen-facebook' );
_x( 'Beta and Up', 'option value', 'nextgen-facebook' );
_x( 'Bitly (suggested)', 'option value', 'nextgen-facebook' );
_x( 'Bottom', 'option value', 'nextgen-facebook' );
_x( 'Buttons HTML', 'option label', 'nextgen-facebook' );
_x( 'Caption:', 'option value', 'nextgen-facebook' );
_x( 'Center', 'option value', 'nextgen-facebook' );
_x( 'checked', 'option value', 'nextgen-facebook' );
_x( 'Content', 'option value', 'nextgen-facebook' );
_x( 'Contractor', 'option value', 'nextgen-facebook' );
_x( 'CSS Sidebar', 'option value', 'nextgen-facebook' );
_x( 'Damaged', 'option value', 'nextgen-facebook' );
_x( 'Dashboard and Features Status', 'lib file description', 'nextgen-facebook' );
_x( 'Day', 'option value', 'nextgen-facebook' );
_x( 'default is %s', 'option value', 'nextgen-facebook' );
_x( '(default)', 'option value', 'nextgen-facebook' );
_x( 'Desktop Only', 'option value', 'nextgen-facebook' );
_x( 'Development and Up', 'option value', 'nextgen-facebook' );
_x( 'Discontinued', 'option value', 'nextgen-facebook' );
_x( 'Display Name', 'option value', 'nextgen-facebook' );
_x( 'Essential Settings', 'lib file description', 'nextgen-facebook' );
_x( 'Every day', 'option value', 'nextgen-facebook' );
_x( 'Every five days', 'option value', 'nextgen-facebook' );
_x( 'Every four days', 'option value', 'nextgen-facebook' );
_x( 'Every month', 'option value', 'nextgen-facebook' );
_x( 'Every six days', 'option value', 'nextgen-facebook' );
_x( 'Every three days', 'option value', 'nextgen-facebook' );
_x( 'Every three weeks', 'option value', 'nextgen-facebook' );
_x( 'Every two days', 'option value', 'nextgen-facebook' );
_x( 'Every two weeks', 'option value', 'nextgen-facebook' );
_x( 'Every week', 'option value', 'nextgen-facebook' );
_x( 'Excerpt Only', 'option value', 'nextgen-facebook' );
_x( 'Excerpt', 'option value', 'nextgen-facebook' );
_x( 'Extension Plugins and Pro Licenses', 'lib file description', 'nextgen-facebook' );
_x( 'Facebook Business Page URL', 'option value', 'nextgen-facebook' );
_x( 'Facebook User URL', 'option value', 'nextgen-facebook' );
_x( 'False', 'option value', 'nextgen-facebook' );
_x( 'Filtered Content', 'option label', 'nextgen-facebook' );
_x( 'First and Last Names', 'option value', 'nextgen-facebook' );
_x( 'Footer', 'option value', 'nextgen-facebook' );
_x( 'Force this value', 'option value', 'nextgen-facebook' );
_x( 'Friday', 'option value', 'nextgen-facebook' );
_x( 'Full Time', 'option value', 'nextgen-facebook' );
_x( 'General Settings', 'lib file description', 'nextgen-facebook' );
_x( 'Google+ Business Page URL', 'option value', 'nextgen-facebook' );
_x( 'Google', 'option value', 'nextgen-facebook' );
_x( 'Google+ URL', 'option value', 'nextgen-facebook' );
_x( 'Header', 'option value', 'nextgen-facebook' );
_x( 'Head Markup', 'option label', 'nextgen-facebook' );
_x( 'Hour', 'option value', 'nextgen-facebook' );
_x( 'HTTP', 'option value', 'nextgen-facebook' );
_x( 'HTTPS', 'option value', 'nextgen-facebook' );
_x( 'If value is empty', 'option value', 'nextgen-facebook' );
_x( 'Image:', 'option value', 'nextgen-facebook' );
_x( 'Image URL Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Image URL Info', 'option label', 'nextgen-facebook' );
_x( 'Instagram Business Page URL', 'option value', 'nextgen-facebook' );
_x( 'Instagram URL', 'option value', 'nextgen-facebook' );
_x( 'In Stock', 'option value', 'nextgen-facebook' );
_x( 'In Store Only', 'option value', 'nextgen-facebook' );
_x( 'Intern', 'option value', 'nextgen-facebook' );
_x( 'Left', 'option value', 'nextgen-facebook' );
_x( 'Limited Availability', 'option value', 'nextgen-facebook' );
_x( 'LinkedIn Company Page URL', 'option value', 'nextgen-facebook' );
_x( 'LinkedIn URL', 'option value', 'nextgen-facebook' );
_x( 'Mobile Only', 'option value', 'nextgen-facebook' );
_x( 'Monday', 'option value', 'nextgen-facebook' );
_x( 'Month', 'option value', 'nextgen-facebook' );
_x( 'Myspace Business Page URL', 'option value', 'nextgen-facebook' );
_x( 'Myspace URL', 'option value', 'nextgen-facebook' );
_x( 'New activation', 'option value', 'nextgen-facebook' );
_x( 'New', 'option value', 'nextgen-facebook' );
_x( 'NextGEN Facebook extension to provide updates for the NextGEN Facebook Pro plugin and its Pro extensions.', 'plugin description', 'nextgen-facebook' );
_x( 'NGFB SSO', 'menu title', 'nextgen-facebook' );
_x( 'Nickname', 'option value', 'nextgen-facebook' );
_x( '(no images)', 'option value', 'nextgen-facebook' );
_x( '[None]', 'option value', 'nextgen-facebook' );
_x( 'No', 'option value', 'nextgen-facebook' );
_x( '(no videos)', 'option value', 'nextgen-facebook' );
_x( 'Off', 'option value', 'nextgen-facebook' );
_x( 'Online Only', 'option value', 'nextgen-facebook' );
_x( 'On', 'option value', 'nextgen-facebook' );
_x( '(option disabled)', 'option value', 'nextgen-facebook' );
_x( 'Other', 'option value', 'nextgen-facebook' );
_x( 'Out of Stock', 'option value', 'nextgen-facebook' );
_x( 'Ow.ly', 'option value', 'nextgen-facebook' );
_x( 'Part Time', 'option value', 'nextgen-facebook' );
_x( 'Per Diem', 'option value', 'nextgen-facebook' );
_x( 'Pinterest Company Page URL', 'option value', 'nextgen-facebook' );
_x( 'Pinterest URL', 'option value', 'nextgen-facebook' );
_x( 'Pre-Order', 'option value', 'nextgen-facebook' );
_x( 'Product Availability Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Product Brand Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Product Color Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Product Condition Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Product Currency Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Product Material Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Product Price Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Product Size Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Public Holidays', 'option value', 'nextgen-facebook' );
_x( 'Recipe Ingredients Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Recipe Instructions Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Refurbished', 'option value', 'nextgen-facebook' );
_x( 'Release Candidate and Up', 'option value', 'nextgen-facebook' );
_x( 'Right', 'option value', 'nextgen-facebook' );
_x( 'Saturday', 'option value', 'nextgen-facebook' );
_x( 'Schema Types', 'option label', 'nextgen-facebook' );
_x( '(settings value)', 'option value', 'nextgen-facebook' );
_x( 'Setup Guide and Other Notes', 'lib file description', 'nextgen-facebook' );
_x( 'Sharing Buttons', 'lib file description', 'nextgen-facebook' );
_x( 'Sharing Styles', 'lib file description', 'nextgen-facebook' );
_x( 'Shortcode', 'option value', 'nextgen-facebook' );
_x( 'Shortened URLs', 'option label', 'nextgen-facebook' );
_x( 'Skype Username', 'option value', 'nextgen-facebook' );
_x( 'Social and Search Image Dimensions', 'lib file description', 'nextgen-facebook' );
_x( 'Social and Search Optimization', 'metabox title', 'nextgen-facebook' );
_x( 'Sold Out', 'option value', 'nextgen-facebook' );
_x( 'Soundcloud Business Page URL', 'option value', 'nextgen-facebook' );
_x( 'SSO Desc.', 'column header', 'nextgen-facebook' );
_x( 'SSO Image', 'column header', 'nextgen-facebook' );
_x( 'SSO Schema', 'column header', 'nextgen-facebook' );
_x( 'Stable / Production', 'option value', 'nextgen-facebook' );
_x( 'Sunday', 'option value', 'nextgen-facebook' );
_x( 'Temporary', 'option value', 'nextgen-facebook' );
_x( 'Thursday', 'option value', 'nextgen-facebook' );
_x( 'TinyURL', 'option value', 'nextgen-facebook' );
_x( 'Title and Excerpt', 'option value', 'nextgen-facebook' );
_x( 'Title Only', 'option value', 'nextgen-facebook' );
_x( 'Top and Bottom', 'option value', 'nextgen-facebook' );
_x( 'Top', 'option value', 'nextgen-facebook' );
_x( 'True', 'option value', 'nextgen-facebook' );
_x( 'Tuesday', 'option value', 'nextgen-facebook' );
_x( 'Tumblr Business Page URL', 'option value', 'nextgen-facebook' );
_x( 'Tumblr URL', 'option value', 'nextgen-facebook' );
_x( 'Twitter Business @username', 'option value', 'nextgen-facebook' );
_x( 'Twitter @username', 'option value', 'nextgen-facebook' );
_x( 'tz', 'option value', 'nextgen-facebook' );
_x( 'unchecked', 'option value', 'nextgen-facebook' );
_x( 'Used', 'option value', 'nextgen-facebook' );
_x( 'User Profile Contact Methods', 'lib file description', 'nextgen-facebook' );
_x( 'Video Embed HTML Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Video URL Custom Field', 'option label', 'nextgen-facebook' );
_x( 'Volunteer', 'option value', 'nextgen-facebook' );
_x( 'WebSite Social Pages and Accounts', 'lib file description', 'nextgen-facebook' );
_x( 'Wednesday', 'option value', 'nextgen-facebook' );
_x( 'Week', 'option value', 'nextgen-facebook' );
_x( 'Widget', 'option value', 'nextgen-facebook' );
_x( 'Year', 'option value', 'nextgen-facebook' );
_x( 'Yes', 'option value', 'nextgen-facebook' );
_x( 'YOURLS', 'option value', 'nextgen-facebook' );
_x( 'Your SSO', 'lib file description', 'nextgen-facebook' );
_x( 'YouTube Business Channel URL', 'option value', 'nextgen-facebook' );
_x( 'YouTube Channel URL', 'option value', 'nextgen-facebook' );
